services:
  - type: web
    name: maebiofuels
    runtime: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && PUPPETEER_CACHE_DIR=/opt/render/project/src/backend/node_modules/.puppeteer_cache npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: DATA_MODE
        value: google
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/backend/node_modules/.puppeteer_cache
